### ISSUE TITLE
Terse header version not recognized : 81

### ISSUE THREAD

**Issue by NickETH** [openmainframeproject/tersedecompress#7]
Hi,
tried to unterse a File for Windows from the IBM download page. Trows an error.
C:\Temp\IBM-Terse>java -jar tersedecompress-5.0.0.jar Updatemanager-WinX64.exp Updatemanager-WinX64.exe
Exception in thread "main" java.io.IOException: Terse header version not recognized : 81
        at org.openmainframeproject.tersedecompress.TerseHeader.CheckHeader(TerseHeader.java:119)
        at org.openmainframeproject.tersedecompress.TerseDecompresser.create(TerseDecompresser.java:32)
        at org.openmainframeproject.tersedecompress.TerseDecompress.process(TerseDecompress.java:100)
        at org.openmainframeproject.tersedecompress.TerseDecompress.main(TerseDecompress.java:113)
What is the problem here?
BR, Nick

**Comment by alexgubanow** [comment]
Hello @NickETH , is the file you have tried to unterse coming from https://public.dhe.ibm.com/storage/tivoli-storage-management/maintenance/client/updatemgr/ ?

**Comment by NickETH** [comment]
Almost.
I tried this one:
https://public.dhe.ibm.com/storage/tivoli-storage-management/patches/client/v8r1/Windows/autodeploy/v8115/8.1.15.2-TIV-TSMBAC-WinX64.exp
But i think, that is the same file...
Thanks for having an eye on it

**Comment by andrew890** [comment]
This seems unlikely to be a TERSE format file?
TERSE is an IBM compression format used for mainframe datasets, created using the AMATERSE utility. Support on non-mainframe platforms is rare, hence this open source implementation to decompress datasets.
A Windows client related file seems unlikely.

**Comment by alexgubanow** [comment]
AMATERSE fails to unterse and if you look at file in hex, it is full of ascii and windows, seems to be an archive, but not PACK or SPACK for sure.
